[package]
name = "tao"
version = "0.5.2"
description = "Cross-platform window manager library."
authors = [
  "Tauri Programme within The Commons Conservancy",
  "The winit contributors"
]
edition = "2018"
keywords = [ "windowing" ]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tauri-apps/tao"
documentation = "https://docs.rs/tao"
categories = [ "gui" ]

[package.metadata.docs.rs]
features = [ "serde", "tray", "dox" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [
  "i686-pc-windows-msvc",
  "x86_64-pc-windows-msvc",
  "i686-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin"
]

[features]
default = [ "tray" ]
tray = [ "tauri-libappindicator" ]
ayatana = [ "libayatana-appindicator" ]
dox = [ "gtk/dox" ]

[dependencies]
instant = "0.1"
lazy_static = "1"
libc = "0.2"
log = "0.4"
serde = { version = "1", optional = true, features = [ "serde_derive" ] }
raw-window-handle = "0.3"
bitflags = "1"
crossbeam-channel = "0.5"

[dev-dependencies]
image = "0.23"
simple_logger = "1.13"

[target."cfg(target_os = \"android\")".dependencies]
ndk = "0.4"
ndk-sys = "0.2"
ndk-glue = "0.4"

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
objc = "0.2"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.24"
core-foundation = "0.9"
core-graphics = "0.22"
dispatch = "0.2"
scopeguard = "1.1"

  [target."cfg(target_os = \"macos\")".dependencies.core-video-sys]
  version = "0.1"
  default_features = false
  features = [ "display_link" ]

[target."cfg(target_os = \"macos\")".build-dependencies]
cc = "1"

[target."cfg(target_os = \"windows\")".dependencies]
parking_lot = "0.11"
unicode-segmentation = "1.8.0"
webview2-com-sys = "0.4.0"
windows = "0.19.0"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
cairo-rs = "0.14"
gio = "0.14"
glib = "0.14"
glib-sys = "0.14"
gtk = { version = "0.14", features = [ "v3_22" ] }
gdk = { version = "0.14", features = [ "v3_22" ] }
gdk-sys = "0.14"
gdk-pixbuf = { version = "0.14", features = [ "v2_36_8" ] }
libayatana-appindicator = { version = "0.1.6", optional = true }
tauri-libappindicator = { version = "0.1.2", optional = true }
x11-dl = "2.18"
